services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: devcontainer
    volumes:
      - ..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity
  db:
    extends:
      file: docker-compose.yml
      service: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql

volumes:
  db: {}
